backend:
  name: git-gateway # For Netlify Git Gateway, or use 'github' for direct GitHub OAuth
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/galleries/main_gallery"
public_folder: "/galleries/main_gallery"
publish_mode: editorial_workflow # Optional: enables a review process

collections:
  - name: "settings"
    label: "Global Settings"
    files:
      - label: "Site Configuration"
        name: "config"
        file: "src/content/settings/config.json" # Store as JSON
        format: "json" # Explicitly set format
        fields:
          - { label: "Site Title Part 1", name: "site_title_part1", widget: "string", default: "Adam" }
          - { label: "Site Title Part 2", name: "site_title_part2", widget: "string", default: "Busina" }
          - { label: "Logo Image", name: "logo_image", widget: "image", required: false }
          - { label: "Header CTA Label", name: "header_cta_label", widget: "string", required: false, default: "Rezervovat focení" }
          - { label: "Header CTA Link", name: "header_cta_link", widget: "string", required: false, default: "/kontakt" }
          - { label: "Footer Intro Text", name: "footer_intro_text", widget: "markdown", required: false }
          - { label: "Contact Email", name: "contact_email", widget: "string", required: false }
          - { label: "Instagram Username (without @)", name: "instagram_username", widget: "string", required: false }
          - { label: "Phone Number", name: "phone_number", widget: "string", required: false }
          - { label: "Copyright Text Base", name: "copyright_text_base", widget: "string", required: false, default: "Adam Busina Photography" }
          - label: "Header Navigation Links"
            name: "header_navigation_links"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          - label: "Footer Navigation Links"
            name: "footer_navigation_links"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          - { label: "Global SEO Description", name: "seo_description", widget: "text", required: false }
          # Homepage specific content now managed under 'Pages' collection

  - name: "galleries"
    label: "Galleries"
    folder: "src/content/galleries"
    create: true
    slug: "{{fields.date}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, picker_utc: true, format: "YYYY-MM-DD", required: true }
      - { label: "Cover Image", name: "cover_image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown", required: false }
      - label: "Images"
        name: "images"
        widget: "list"
        summary: "{{fields.alt}}"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Alt Text", name: "alt", widget: "string" }
      - { label: "Page SEO Title", name: "seo_title", widget: "string", required: false, hint: "Optional. Defaults to gallery title." }
      - { label: "Page SEO Description", name: "seo_description", widget: "text", required: false, hint: "Optional. Defaults to global SEO description or gallery description." }

  - name: "service_packages"
    label: "Service Packages"
    folder: "src/content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug (URL part)", name: "slug", widget: "string", required: false, hint: "Optional. If empty, generated from title." }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Inclusions"
        name: "inclusions"
        widget: "list"
        summary: "{{fields.text}}"
        fields:
          - { label: "Text", name: "text", widget: "string"}
      - { label: "Price", name: "price", widget: "string", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Order (Sort Priority)", name: "order", widget: "number", required: false, hint: "Lower numbers appear first. Used for non-pinned items." }
      - { label: "Pinned (Display First)", name: "pinned", widget: "boolean", default: false, required: false, hint: "Pinned items appear before all non-pinned items." }

  - name: "testimonials"
    label: "Testimonials"
    folder: "src/content/testimonials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{author_name}}"
    fields:
      - { label: "Author Name", name: "author_name", widget: "string" }
      - { label: "Author Context (e.g., 'Client' or 'Couple from Wedding X')", name: "author_context", widget: "string", required: false }
      - { label: "Quote", name: "quote", widget: "text" } # Textarea widget
      - { label: "Display on Homepage", name: "display_on_homepage", widget: "boolean", default: false }

  - name: "pages"
    label: "Static Pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "src/content/pages/home.json" # Homepage content stored as JSON
        format: "json"
        fields:
          - { label: "Page Title (for SEO & tab)", name: "title", widget: "string", default: "Domů" }
          - { label: "Hero Heading", name: "homepage_hero_heading", widget: "string", default: "Zachytím vaše příběhy" }
          - { label: "Hero Subheading", name: "homepage_hero_subheading", widget: "markdown", default: "Autentické a emotivní fotografie, které vám zůstanou navždy." }
          - { label: "Hero CTA Label", name: "homepage_hero_cta_label", widget: "string", default: "Prohlédnout portfolio" }
          - { label: "Hero CTA Link", name: "homepage_hero_cta_link", widget: "string", default: "/galerie" }
          - label: "Carousel Images"
            name: "carousel_images"
            widget: "list"
            summary: "{{fields.alt}}"
            hint: "Images for the homepage photo carousel. Ensure paths are relative to /public (e.g. /galleries/main_gallery/image.jpg) or select from media library."
            fields:
              - { label: "Image", name: "src", widget: "image" } # 'src' to match prop expected by carousel
              - { label: "Alt Text", name: "alt", widget: "string", default: "Carousel image" }
          - { label: "Gallery CTA Label (below carousel)", name: "gallery_cta_label", widget: "string", default: "Zobrazit celou galerii" }
          - { label: "Gallery CTA Link (below carousel)", name: "gallery_cta_link", widget: "string", default: "/galerie" }
          
          # New Features Section
          - label: "Features Section Heading"
            name: "features_section_heading"
            widget: "string"
            required: false
          - label: "Features Section Intro"
            name: "features_section_intro"
            widget: "markdown"
            required: false
          - label: "Features Section CTA Label"
            name: "features_section_cta_label"
            widget: "string"
            required: false
          - label: "Features Section CTA Link"
            name: "features_section_cta_link"
            widget: "string"
            required: false
          - label: "Feature Items (3 items expected)"
            name: "feature_items"
            widget: "list"
            summary: "{{fields.heading}}"
            min: 3 # Ensuring 3 items
            max: 3 # Ensuring 3 items
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "Image Alt Text (Image 1: aimage5, Image 2: aimage1, Image 3: aimage7)", name: "image_alt", widget: "string" }

          # New About Me Section
          - label: "About Section - Pre-heading"
            name: "about_section_preheading"
            widget: "string"
            required: false
          - label: "About Section - Heading"
            name: "about_section_heading"
            widget: "string"
            required: false # Assuming it can be optional if the whole section can be
          - label: "About Section - Paragraph"
            name: "about_section_paragraph"
            widget: "markdown"
            required: false
          - label: "About Section - CTA Label"
            name: "about_section_cta_label"
            widget: "string"
            required: false
          - label: "About Section - CTA Link"
            name: "about_section_cta_link"
            widget: "string"
            required: false
          - label: "About Section - Image Alt Text (for profil1.jpg)"
            name: "about_section_image_alt"
            widget: "string"
            required: false
            default: "Portrait photo"

          - label: "About Section - Icon Features"
            name: "about_section_icon_features"
            widget: "list"
            required: false
            summary: "{{fields.heading}} - Icon: {{fields.icon_type}}"
            fields:
              - { label: "Icon Type", name: "icon_type", widget: "select", options: ["camera", "person", "clock"], default: "camera" }
              - { label: "Heading", name: "heading", widget: "string" }

          - { label: "Page SEO Description", name: "seo_description", widget: "text", required: false, hint: "Optional. If empty, uses Global SEO Description." }
          # ... other homepage specific sections like "Why Me", "About Snippet" can be added as fields here ...

          # New Alternating Icon/Text Features Section
          - label: "Icon Features Section Heading"
            name: "icon_features_section_heading"
            widget: "string"
            required: false
          - label: "Icon Features Section Intro"
            name: "icon_features_section_intro"
            widget: "markdown"
            required: false
          - label: "Icon Feature Items (3 items expected - icon3-1, icon2-1, icon1-1)"
            name: "icon_feature_items"
            widget: "list"
            summary: "{{fields.heading}}"
            min: 3
            max: 3
            fields:
              - { label: "Heading", name: "heading", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
              - { label: "Icon Alt Text", name: "image_alt", widget: "string" }

          # New Testimonials Section fields
          - label: "Testimonials Section Heading"
            name: "testimonials_section_heading"
            widget: "string"
            required: false # Assuming can be optional
          - label: "Testimonials Section CTA Label"
            name: "testimonials_section_cta_label"
            widget: "string"
            required: false
          - label: "Testimonials Section CTA Link"
            name: "testimonials_section_cta_link"
            widget: "string"
            required: false

          # Contact Form Section
          - label: "Contact Form Section Heading"
            name: "contact_section_heading"
            widget: "string"
            required: false

      - label: "Galerie Page" # New entry for Galerie page
        name: "galerie"
        file: "src/content/pages/galerie.md"
        fields:
          - { label: "Page Title (for SEO & tab)", name: "title", widget: "string", default: "Galerie" }
          - { label: "Introductory Paragraph", name: "intro_paragraph", widget: "markdown", required: false }
          - { label: "Page SEO Description", name: "seo_description", widget: "text", required: false }

      - label: "About Page"
        name: "about"
        file: "src/content/pages/omne.md" # Will render at /omne
        fields:
          - { label: "Page Title (for SEO & tab)", name: "title", widget: "string", default: "O mně" }
          - { label: "Hero Heading", name: "hero_heading", widget: "string", required: false }
          - { label: "Hero Background Image", name: "hero_background_image", widget: "image", required: false, hint: "Image used for the hero section background. Should be omne-hero.jpg" }
          - { label: "Main Content (for styled rectangle)", name: "body", widget: "markdown" }
          - { label: "Text After Styled Rectangle (bold text)", name: "after_text", widget: "string", required: false }
          - { label: "Gallery CTA Label", name: "gallery_cta_label", widget: "string", required: false, default: "Moje práce" }
          - { label: "Gallery CTA Link", name: "gallery_cta_link", widget: "string", required: false, default: "/galerie" }
          - { label: "Contact CTA Label", name: "contact_cta_label", widget: "string", required: false, default: "Napište mi" }
          - { label: "Contact CTA Link", name: "contact_cta_link", widget: "string", required: false, default: "/kontakt" }
          - { label: "Page SEO Description", name: "seo_description", widget: "text", required: false }

      - label: "Services Page (General Info)"
        name: "services_info" # This is for the main /sluzby page content, not the individual packages
        file: "src/content/pages/sluzby.md" # Will render at /sluzby
        fields:
          - { label: "Page Title (for SEO & tab)", name: "title", widget: "string", default: "Služby" }
          - { label: "Hero Heading", name: "hero_heading", widget: "string", required: false }
          - { label: "Hero Background Image", name: "hero_background_image", widget: "image", required: false }
          - { label: "Hero CTA Text", name: "hero_cta_text", widget: "markdown", required: false }
          - { label: "Hero CTA Label", name: "hero_cta_label", widget: "string", required: false, default: "Nezávazně poptat" }
          - { label: "Hero CTA Link", name: "hero_cta_link", widget: "string", required: false, default: "/kontakt" }
          - { label: "Main Content/Intro (above service packages)", name: "body", widget: "markdown", required: false }
          - { label: "Travel Fee Text", name: "travel_fee_text", widget: "string", required: false }
          - { label: "Gallery CTA Label", name: "gallery_cta_label", widget: "string", required: false, default: "Ukázky mé práce" }
          - { label: "Gallery CTA Link", name: "gallery_cta_link", widget: "string", required: false, default: "/galerie" }
          - { label: "Page SEO Description", name: "seo_description", widget: "text", required: false }

      - label: "Contact Page"
        name: "contact"
        file: "src/content/pages/kontakt.md" # Will render at /kontakt
        fields:
          - { label: "Page Title (for SEO & tab)", name: "title", widget: "string", default: "Kontakt" }
          - { label: "Contact Section Heading", name: "contact_section_heading", widget: "string", required: false, default: "Kontakt"}
          - { label: "Display Email", name: "contact_email_detail", widget: "string", required: false }
          - { label: "Display Phone", name: "contact_phone_detail", widget: "string", required: false }
          - { label: "Instagram URL", name: "contact_instagram_url", widget: "string", required: false, hint: "Full URL, e.g., https://instagram.com/username" }
          - { label: "Billing Details Heading", name: "billing_details_heading", widget: "string", required: false, default: "Fakturační údaje" }
          - { label: "Billing Details Content", name: "billing_details_content", widget: "markdown", required: false }
          - { label: "Form Heading", name: "form_heading", widget: "string", required: false, default: "Napište mi" }
          - { label: "Form Intro Text", name: "form_intro_text", widget: "markdown", required: false }
          - { label: "Map Embed Code (HTML)", name: "map_embed_code", widget: "text", required: false } # Using text for HTML embed
          - { label: "Main Content (e.g., above or below form)", name: "body", widget: "markdown", required: false }
          - { label: "Page SEO Description", name: "seo_description", widget: "text", required: false }

      - label: "Gallery Overview Page" # For the main /galleries page
        name: "gallery_overview"
        file: "src/content/pages/galerie.md" # Will render at /galerie
        fields:
          - { label: "Page Title (for SEO & tab)", name: "title", widget: "string", default: "Galerie" }
          - { label: "Page Heading", name: "page_heading", widget: "string", required: false, default: "Moje Portfolio" }
          - { label: "Intro Text", name: "intro_text", widget: "markdown", required: false }
          - { label: "Disclaimer Text", name: "disclaimer_text", widget: "markdown", required: false }
          - { label: "Page SEO Description", name: "seo_description", widget: "text", required: false }

          # ... existing code ... 